[http_client]
api_url = "https://api.apilayer.com/exchangerates_data/convert"
api_key = "MEnPsCu35NliftxNK0B89qLw98il9akk"

[kafka_client]
kafka_host = "localhost:9092"
feedback_topic = "support.feedback.topic"